FirstProject/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include("polls.urls",namespace='polls'))
]

FirstProject/mysite/polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'
urlpatterns = [

    path('', views.index, name="index"),
    path('<q_id>/', views.detail, name="detail"),
    path('<q_id>/results/', views.results, name="results"),
    path('<q_id>/vote/', views.vote, name="vote"),
]

FirstProject/mysite/polls/models.py
from django.db import models

# Create your models here.
class Question(models.Model):

    qus_text= models.CharField(max_length=200)
    pub_date = models.DateTimeField("Date Published")

    def __str__(self):
        return self.qus_text


class Choice(models.Model):
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    qus_id = models.ForeignKey(Question, on_delete=models.CASCADE)

    def __str__(self):
        return self.choice_text

FirstProject/mysite/polls/views.py
from django.shortcuts import render, get_object_or_404
from .models import Question
from django.http import HttpResponse,HttpResponseRedirect
from django.urls import reverse
# Create your views here.
def index(request):
    l_qus = Question.objects.order_by('-pub_date')[:5]
    context = {'l_qus':l_qus}
    return render(request, 'polls/index.html', context=context)

def detail(request, q_id):
    qus = get_object_or_404(Question, pk=q_id)
    return render(request, "polls/detail.html", context={'qus':qus})

def results(req, q_id):

    qus =  get_object_or_404(Question, pk=q_id)
    return render(req, 'polls/results.html', context={'qus':qus})

def vote(req, q_id):
    qus = get_object_or_404(Question, pk=q_id)
    try:
        selected_choice = qus.choice_set.get(pk = req.POST['choice'])
    except:
        return render(req, "polls:detail.html", {'qus':qus, 'error_message': "Please Select a choice"})
    else:
        selected_choice.votes +=1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(qus.id,)))

FirstProject/mysite/polls/templates/polls/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<hr>
    <p>Header</p>
<hr>
    {% block main_content %}
    {% endblock %}
    {% include 'polls/footer.html' %}
</body>
</html>

FirstProject/mysite/polls/templates/polls/detail.html
{% extends  'polls/base.html' %}
{% block main_content %}
    <h1>{{ qus.qus_text}}</h1>
    {% if err_msg %} <p><strong> {{ error_message }}</strong></p>{% endif %}

    <form action="{% url 'polls:vote' qus.id %}" method="post">
        {% csrf_token %}
        {% for choice in qus.choice_set.all%}
            <input type="radio" name="choice" id="choice{{forloop.counter}}" value="{{choice.id}}"/>
        <label for="choice{{forloop.counter}}">{{choice.choice_text}}</label><br>
        {%endfor%}
        <input type="submit" value="vote">
    </form>
    <!--<ul>-->
        <!--{% for choice in qus.choice_set.all %}-->
        <!--<li>{{choice.choice_text}}</li>-->
        <!--{%endfor%}-->
    <!--</ul>-->

{% endblock %}

FirstProject/mysite/polls/templates/polls/footer.html
<hr>
    <p>Footer</p>
</hr>

FirstProject/mysite/polls/templates/polls/index.html
{% extends  'polls/base.html' %}

{% block main_content %}


    {% if l_qus %}
        <ul>
            {% for qus in l_qus %}
                <li><a href={% url "polls:detail" qus.id %}><b>{{qus.qus_text}}</b></a></li>
            {% endfor %}
        </ul>
    {% else %}
        <p>You don't have any Qus. please Add some. </p>
    {% endif %}

{% endblock %}

FirstProject/mysite/polls/templates/polls/results.html
{% extends  'polls/base.html' %}

{% block main_content %}

    <h1>{{ qus.qus_text}}</h1>

    <ul>
        {% for choice in qus.choice_set.all %}
        <li>{{ choice.choice_text}} -- {{ choice.votes}} vote{{choice|pluralize}}</li>
        {% endfor %}
    </ul>
    <a href="{% url 'polls:detail' qus.id %}"> Vote Again?</a>
<!--<li><a href={% url "polls:detail" qus.id %}><b>{{qus.qus_text}}</b></a></li>-->
{% endblock %}